name: Feature Request
description: Suggest a feature or enhancement to make Kuralit even better.
title: "[Feature Request] "
labels: ["enhancement"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an idea! Your feature requests help shape the future of Kuralit.
        
        **Before submitting:**
        - Check if a similar feature has already been requested
        - Review the [documentation](https://docs.kuralit.com) to see if the feature already exists
        - Consider if this aligns with Kuralit's focus on mobile AI agents
  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of Kuralit would this feature affect?
      options:
        - Python SDK (Server)
        - Flutter SDK (Client)
        - React Native SDK (Future)
        - Tool System
        - WebSocket/Protocol
        - Audio/STT/VAD/Turn Detection
        - UI Templates
        - Documentation
        - Examples
        - Firebase Integration (Future)
        - Other
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Provide a clear and concise explanation of the problem or limitation you're facing. Why is this feature needed?
      placeholder: |
        Example: "I'm building a mobile app with Kuralit and I need [feature] because [reason]. Currently, I have to [workaround] which is [problem]."
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Explain your ideal solution. How should this feature work? Be as detailed as possible.
      placeholder: |
        Describe:
        - How the feature should function
        - API design or interface changes
        - UI/UX changes (if applicable)
        - Integration points with existing Kuralit components
        - Example usage
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful.
      placeholder: |
        Example: "When building a customer support chatbot, I need to [use case] so that [benefit]."
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Have you found any workarounds or alternative solutions? Share other approaches you've tried or thought about.
      placeholder: |
        - Workaround 1: [description]
        - Workaround 2: [description]
        - Why these don't work: [reason]
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include any extra information that might be helpful (screenshots, examples of similar features in other frameworks, relevant links, mockups).
    validations:
      required: false
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: We welcome contributions! Let us know if you'd like to help implement this feature.
      options:
        - label: Yes, I'd love to work on it!
        - label: I'm open to collaborating but need guidance.
        - label: No, I'm just sharing the idea.
    validations:
      required: false